### ISSUE TITLE
When build fails. Gulp stops watching.

### ISSUE THREAD

**Issue by seifsg** [zacky1972/gulp-parcel#4]
Hello.

I'm having an issue. As described in here:
https://stackoverflow.com/questions/48113020/gulp-4-browsersync-in-parallel-with-pug-and-parceljs-tasks-in-series

Can you please help?
Thanks!

**Comment by zacky1972** [comment]
I've test only on Mac, so Windows PC might be impossible to run gulp-parcel.

Perhaps, This PR is effective: https://github.com/zacky1972/gulp-parcel/pull/5

I'll confirm it on Windows PC as soon as possible. Thank you.
